### PR TITLE
Update NuGet package description

### PR DESCRIPTION
**Pull request by David-Engel**
Addresses #1963
Make the description clear that it is a replacement for SDS and is the latest library for SQL connectivity.

Ideally, the first couple of lines would help differentiate which library to use when bringing it in to VS:
image

CC: @ericstj , @sharwell

### CODE REVIEW

**Comment by ericstj** [comment]
This looks good to me.  @sharwell would this new description help solve the problem you raised?

**Review by JRahnama — APPROVED** [review]

**Review by lcheunglci — APPROVED** [review]

**Comment by sharwell** [comment]
Yes, the new description would have saved me time. 👍

**Comment by ErikEJ** [comment]
Could also be "The current" or "The modern"

**Comment by yerald-mora** [comment]
@David-Engel i'm still not able to see the new descriptions when browsing the packages in Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.5.2
image

**Comment by yerald-mora** [comment]
@David-Engel i'm still not able to see the new descriptions when browsing the packages in Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.5.2
image

**Comment by David-Engel** [comment]
@yerald-mora You will only see it for releases starting with 5.2 preview 1.

https://www.nuget.org/packages/Microsoft.Data.SqlClient/5.2.0-preview3.23201.1#readme-body-tab

There is a way to edit the readme for previous releases, but I haven't looked into that, yet.

**Pull request merged**
