### PR TITLE
Add nuget auditing at the sln level

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by JRahnama** [comment]
> /azp run

Sorry I had to force stop the CI pipelines to fix some issues there. It is rerunning again.

**Comment by SimonCropp** [comment]
@JRahnama no worries. thanks for letting me know

**Comment by SimonCropp** [comment]
@JRahnama still seems to be failing during some unrelated tests. any ideas?

**Comment by JRahnama** [comment]
> @JRahnama still seems to be failing during some unrelated tests. any ideas?

General pipeline failures are addressed and it is expected to work properly. Failures are due to some of the changes I made which will be addressed tomorrow (Monday morning).

**Comment by cheenamalhotra** [comment]
This isn't needed to be enabled as we have Component Gov enabled for nightly builds that flag any vuln package dependencies, and this is upon us to address any vuln dependencies on time.

**Pull request closed without merging**
