### PR TITLE
Align ADP.IsEmpty -> string.IsNullOrEmpty

### PR DESCRIPTION
**Pull request by MichelZ**
This PR simply changes ADP.IsEmpty to string.IsNullOrEmpty to align netfx with netcore

Part of #2953

### CODE REVIEW

**Review by benrr101 — APPROVED** [review]
Why this method exists, I have no idea. I will look forward to removing it soon enough.

**Review by cheenamalhotra — APPROVED** [review]

**Comment by MichelZ** [comment]
@cheenamalhotra Could you also run this pipeline? Thx :)

**Comment by ErikEJ** [comment]
@benrr101 IsNullOrEmpty did not exist in .NET Framework 1 😅

**Pull request merged**
