### PR TITLE
Set _parentOperationStarted in ExecuteReaderAsync continuation

### PR DESCRIPTION
**Pull request by ahydrax**
This fixes https://github.com/dotnet/SqlClient/issues/1506.

The problem was there https://github.com/dotnet/SqlClient/blob/main/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlCommand.cs#L2777
`_parentOperationStarted ` flag has to be set explicitly after `ExecuteReaderAsync` i.e. in its continuation.

Reproduction code is available here: https://gist.github.com/AndrewP-GH/1e1ad8d2b864ed549e31e5f03fee015e

### CODE REVIEW

**Comment by Wraith2** [comment]
Does this prevent the event that occurs after the parent is unset from having a guid at all? Is that better than saving the parent guid and using it later?

**Comment by ahydrax** [comment]
@Wraith2 
> Does this prevent the event that occurs after the parent is unset from having a guid at all?

Since its hard to write a non-flaky test for that case I can only assume that. At least now it looks like a correct control flow: we for sure unset the flag right after child operation completes. I tried to launch a repro code several times and got no issues with that.
I was also thinking about attaching `_parentOperationStarted = false;` in a separated continuation to outer task. But from my perspective it just adds an extra overhead for TaskScheduler. What do you think?

> Is that better than saving the parent guid and using it later?

It might be also a solution to be discussed.

**Comment by ahydrax** [comment]
@Wraith2 could you help me with test pipeline? https://dev.azure.com/sqlclientdrivers-ci/sqlclient/_build/results?buildId=47677&view=logs&jobId=6399d89d-3d30-5fff-3e92-07bbaf7ebe2f&j=6399d89d-3d30-5fff-3e92-07bbaf7ebe2f&t=d757e160-f926-47ff-8096-49a8c7da6621 it looks like tests didn't even start

**Comment by Wraith2** [comment]
I don't have CI access either. You can push a tiny change commit, close and re-open the PR or just wait if you think they're false positives and the MS team will probably re-run them when they get to review.

**Comment by ahydrax** [comment]
@Wraith2 the pipeline is green now. Could you assign or tag someone who can review this?

**Comment by Wraith2** [comment]
I'm an external contributor like you, I don't have any permissions. The MS team will pick it up when they can.

**Comment by ahydrax** [comment]
Any news? We would like to have fixed tracing 😸 
@Wraith2 @johnnypham @DavoudEshtehari @David-Engel

**Comment by DavoudEshtehari** [comment]
@ahydrax, attempting to run the [repro](https://gist.github.com/AndrewP-GH/1e1ad8d2b864ed549e31e5f03fee015e) with this change using a .NET 6.0 console app, I got the NRE while it doesn't break with the latest source code. 
Can you verify if it's only me?

```
Unhandled exception. System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken) in C:\xxx\src\Microsoft.Data.SqlClient\netcore\ref\Microsoft.Data.SqlClient.cs:line 892
   at ConsoleApp1.Program.<>c.<<RunTest>b__1_0>d.MoveNext() in C:\xxx\ConsoleApp1\Program.cs:line 36
--- End of stack trace from previous location ---
   at ConsoleApp1.Program.<>c.<<RunTest>b__1_0>d.MoveNext() in C:\xxx\ConsoleApp1\Program.cs:line 40
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at ConsoleApp1.Program.RunTest() in C:\xxx\ConsoleApp1\Program.cs:line 33
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ConsoleApp1.Program.Main(String[] args) in C:\xxx\ConsoleApp1\Program.cs:line 14
```

**Comment by David-Engel** [comment]
I've run the repro with and without the fix. In both cases, I still get empty GUIDs in the repro. There are usually fewer empties with the fix, but something is still missing. For reference, without the fix, I see 20-30 empty GUIDs. With the fix, it's 10-15.

**Comment by ahydrax** [comment]
Thanks for update!
@David-Engel could you tell me which framework/os you used to run the repro? I don't get empty guids on windows 11 x64

**Comment by DavoudEshtehari** [comment]
I got the empty GUIDs on Win 10 (version 21H2) and `.NET 6.0` using a core i7 CPU.

**Comment by ahydrax** [comment]
I tried to reproduce this bug on `5.1.0` and seems it's fixed now.

**Pull request closed without merging**
