### PR TITLE
Add missing refs for RowCopied

### LINKED ISSUE #505: RowsCopied not available in 2.0 preview 2
### Describe the bug
I cannot use RowsCopied event, does not exist in SqlBulCopy class in 2.0 preview 2, event though readme states it should be available.

### To reproduce

The code below does not compile. I expected it to.

```
            using (var sqlConnection = new SqlConnection("Data Source=(localdb)\\mssqllocaldb;Initial Catalog=Northwind;Integrated Security= true"))
            {
                sqlConnection.Open();
                using (var bulkCopy = new SqlBulkCopy(sqlConnection))
                {
                    bulkCopy.DestinationTableName = "Shippers";
                    bulkCopy.WriteToServer(new DataTable());
                    var rows = bulkCopy.RowsCopied;
                }
            }
```
### Further technical details
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="2.0.0-preview2.20084.1" />
  </ItemGroup>
</Project>

```

### PR DESCRIPTION
**Pull request by cheenamalhotra**
Fixes #505

### CODE REVIEW

**Comment by ErikEJ** [comment]
LGTM

**Comment by ErikEJ** [comment]
When do you currently plan to publish preview3 ?

**Comment by cheenamalhotra** [comment]
Hi @ErikEJ 

Our plan is to release Preview 3 sooner in 2-3 weeks, definitely in this month.

**Comment by ErikEJ** [comment]
Perfect! I will postpone my blog post till then!

**Pull request merged**
