### PR TITLE
XML Documentation Fixes - Batch 7

### PR DESCRIPTION
**Pull request by benrr101**
**Description**: This is the last batch of XML documentation fixes for the Microsoft.Data.SqlClient namespace. This one is pretty easy compared to the others. This is work towards #2013

**Testing**: I verified they come up correctly in the IDE, so we should be good.

### CODE REVIEW

**Comment by JRahnama** [comment]
@benrr101 the failures are related to the changes
```MSBuild
##[error]src\Microsoft.Data.SqlClient\netfx\ref\Microsoft.Data.SqlClient.cs(1845,13): Error CS1734: XML comment on 'SqlTransaction.Save(string)' has a paramref tag for 'savePoint', but there is no parameter by that name
```

**Comment by benrr101** [comment]
@JRahnama Who changed the name from `savePoint` to `savePointName`?? 😉 
Build issue should be fixed now

**Review by mdaigle — APPROVED** [review]

**Comment by JRahnama** [comment]
> @JRahnama Who changed the name from `savePoint` to `savePointName`?? 😉 Build issue should be fixed now

Was it me??? 😆

**Pull request merged**
