### PR TITLE
Fix link

### PR DESCRIPTION
**Pull request by danielmarbach**

### CODE REVIEW

**Comment by cheenamalhotra** [comment]
Thanks for catching that! Please also update Changelog with same change.

**Comment by danielmarbach** [comment]
As far as my willingness to help you out goes I have no idea where the changelog is. I spent a few seconds browsing around the repo but couldn't find it. Do you mind pointing me in the right direction?

**Comment by Wraith2** [comment]
Looks like it's in the root, https://github.com/dotnet/SqlClient/blob/master/CHANGELOG.md

**Comment by danielmarbach** [comment]
Done

**Pull request merged**
