### PR TITLE
Edit | 4.0.1 update release note

### PR DESCRIPTION
**Pull request by DavoudEshtehari**

### CODE REVIEW

**Review by johnnypham — APPROVED** [review]

**Comment by johnnypham** [comment]
I had some suggestions in #1474 which were never reviewed. I can't make suggestions in the changes so can you manually add them?

**Comment by DavoudEshtehari** [comment]
> I had some suggestions in #1474 which were never reviewed. I can't make suggestions in the changes so can you manually add them?

I though you was agree with the PR when you approved it! Are you sure you want them to be applied?

**Comment by DavoudEshtehari** [comment]
Done

**Review by Kaur-Parminder — APPROVED** [review]

**Comment by johnnypham** [comment]
> > I had some suggestions in #1474 which were never reviewed. I can't make suggestions in the changes so can you manually add them?
> 
> I though you were agree with the PR when you approved it! Are you sure you want them to be applied?

The conversations were resolved even though my changes weren't reviewed. I then reopened the conversations to ask for a review again. My mistake, I shouldn't have approved it without ensuring my suggestions would actually be seen. Yes, I want them applied, the original wording is awkward imo.

**Review by johnnypham — CHANGES_REQUESTED** [review]
Changes made to /CHANGELOG.md during the review of #1474 weren't applied to /release-notes/4.0/4.0.1.md.

**Comment by DavoudEshtehari** [comment]
> Changes made to /CHANGELOG.md during the review of #1474 weren't applied to /release-notes/4.0/4.0.1.md.

Nice catch. Done!

**Review by johnnypham — APPROVED** [review]

**Pull request merged**
