### PR TITLE
Sync ref project references with runtime projects

### PR DESCRIPTION
**Pull request by edwardneal**
This PR syncs the references of the reference assemblies with those of their respective runtime assemblies. Doing so enables MSBuild's ResolveAssemblyReferences and GenerateBindingRedirects targets to generate the correct binding redirects - so if a downstream library references a later version of Azure.Core or Azure.Identity, VS will generate binding redirects so that SqlClient will use that later version.

Early testing looks promising and I think it'll resolve the issue - but for now, it just relates to #2541 and to #2082.

### CODE REVIEW

**Review by benrr101 — APPROVED** [review]
This change seems pretty reasonable to me. Let's get the merge conflicts fixed and make sure the test runs pass and we'll get it merged. Thanks for looking into this!

**Comment by edwardneal** [comment]
Thanks @benrr101 - just merged!

**Review by mdaigle — APPROVED** [review]

**Review by cheenamalhotra — APPROVED** [review]

**Comment by edwardneal** [comment]
@cheenamalhotra can I port this back to the next releases of 5.1 and 5.2? This should let us close #2541 for the remaining supported versions.

**Comment by cheenamalhotra** [comment]
Sure, that makes sense.

**Pull request merged**
