### PR TITLE
Update README file

### PR DESCRIPTION
**Pull request by JRahnama**
This PR updates the README file that will eventually be added to the SqlClient package on nuget.org, replacing the [current README file](https://www.nuget.org/packages/Microsoft.Data.SqlClient#readme-body-tab). 

@David-Engel, @imasud00, @saurabh500, @cheenamalhotra, please review and provide any feedback or suggest changes if you’d prefer different content or a more detailed description.

A subsequent PR will be made to include the updated README file in our NuGet package.

### CODE REVIEW

**Review by ErikEJ — COMMENTED** [review]
Is the Gitter room active?

Suggest changing .NET Core to .NET throughout

**Comment by David-Engel** [comment]
I pushed some general updates throughout, including @ErikEJ 's suggestions.

**Review by David-Engel — APPROVED** [review]

**Comment by JRahnama** [comment]
> Is the Gitter room active?

seems like it is active, not sure.

**Comment by David-Engel** [comment]
> > Is the Gitter room active?
> 
> ~seems like it is active, not sure.~
> 
> I noticed that David removed the link.

Yeah, the room is pretty much dead.

**Review by dauinsight — APPROVED** [review]

**Pull request merged**
