### PR TITLE
Code Cleanup | `123 == x` => `x == 123` etc

### PR DESCRIPTION
**Pull request by benrr101**
**Description**: In the latest in my series of code cleanup PRs to remove Yoda conditions, this PR flips conditions where `0 == x` to `x == 0`. This is also applied for >, >=, <, <=, and !=.

**AI Analysis**:
image

**Testing**: Again, if it builds and passes CI, I think it's safe.

### CODE REVIEW

**Comment by saurabh500** [comment]
Have you validated the AI analysis? Usually these come with an asterisk saying "AI content may be incorrect"

**Comment by saurabh500** [comment]
Also @benrr101 please open a tracking issue for this work and describe the significance of doing this for tracking purposes. 
I see references to Yoda conditions but the term hasn't been defined. 
Please provide citations for the significance of these changes. 
They may be safe, but I am not sure what would happen if we dont take these changes. 
As of now I am seeing more problems with such large code hygeine PRs than the benefits that may come due to it.

**Comment by JRahnama** [comment]
@saurabh500 I think, we can also have  [RoslynAnalyzer](https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/#enforce-team-coding-standards) to enforce some coding standards to prevent this in future as this cannot be done in editorconfig file.

**Comment by saurabh500** [comment]
Please hold off on the merge of this PR till we drive https://github.com/dotnet/SqlClient/pull/2714 and JSON work to conclusion.

**Comment by benrr101** [comment]
@saurabh500 the "ai analysis" is provided for your convenience. If you don't trust it, you are free to analyze all 104 changed files, but considering most people's eyes will glaze over after about 5 files, this analysis of the patch file is provided to give a summary of the changes and their safety.

Yoda conditions are a name for conditions whose expressions are reversed from their typical ordering. https://en.wikipedia.org/wiki/Yoda_conditions The reason for making these changes is to make the code more readable and supportable by changing the order to what is typical for both programming and the mental english translation ("x is greater than 0" is more natural than "0 is less than x").

If we do not take these changes, nothing happens, although I will be mentally cursing at the code each time I encounter one of these backwards conditions when I have to support it in the future. Considering the support that was given to making similar changes for null comparisons, I believe other engineers will be mentally cursing the code each time they encounter them, as well. Code hygiene is important and in the absence of anyone else feeling brave enough stand up for it, I'll gladly take up that torch.

**Comment by cheenamalhotra** [comment]
Moving to Backlog due to unresolved conflicts.

**Comment by benrr101** [comment]
Also closing this one since too many things have changed since it last had attention.

**Pull request closed without merging**
