### PR TITLE
Fix populating of TYPE_SCHEMA column in StructuredTypeMembers metadata

### PR DESCRIPTION
**Pull request by tf-micwil**
Fixes for #1498 

- Updated the FROM clause on the SELECT statement for StructuredTypeMembers metadata to use the schema name from sys.table_types.
- Added StructuredTypeMembers to SqlClientMetaDataCollectionNames
- Added unit tests for StructuredTypeMembers

I was unable to run the tests as I don't have access to a required nuget package in test project.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/SqlClient?pullRequest=1500) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/SqlClient?pullRequest=1500) before we can accept your contribution.<br/><br/>:x: tf-micwil [sign now](https://cla.dotnetfoundation.org/dotnet/SqlClient?pullRequest=1500)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/SqlClient?pullRequest=1500) it.</sub>

**Comment by Wraith2** [comment]
Looks good in general. 

The nuget comes from the package source in the nuget.config file in the src directory, everything below that directory should pick it up. I can run tests locally but I've been doing it for a while so if something has broken I might already have the nuget packages locally. Specifically which packages failed to restore?

**Comment by tf-micwil** [comment]
@Wraith2: Microsoft.Data.SqlClient.ManualTesting.Test is reporting that Microsoft.DotNet.RemoteExecutor (5.0.0-beta.20206.4) is not available in the dotnet-public package source.

**Comment by Wraith2** [comment]
I don't have that package locally and I haven't had that problem (but then i haven't opened any PR's in a while since I.m waiting.). Remote executor is needed for tests that are going to run in the ci as an external process so you may not need it to check your work locally.

**Review by David-Engel — APPROVED** [review]

**Review by DavoudEshtehari — APPROVED** [review]

**Pull request merged**
