### PR TITLE
Avoid "early" access to SqlAuthenticationProviderManager.Instance

### PR DESCRIPTION
**Pull request by 0xced**
Accessing `SqlAuthenticationProviderManager.Instance` inside the `SqlInternalConnectionTds` constructor forces to load `Microsoft.Identity.Client.dll` since the `ActiveDirectoryAuthenticationProvider` constructor references the `DeviceCodeResult` type (which is part of `Microsoft.Identity.Client`).

```
   at Microsoft.Data.SqlClient.ActiveDirectoryAuthenticationProvider..ctor(String applicationClientId)
   at Microsoft.Data.SqlClient.SqlAuthenticationProviderManager.SetDefaultAuthProviders(SqlAuthenticationProviderManager instance)
   at Microsoft.Data.SqlClient.SqlAuthenticationProviderManager..cctor()
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool, Func`3 accessTokenCallback)
```

Accessing `SqlAuthenticationProviderManager.Instance` later (inside the `GetFedAuthToken` method) makes it possible to remove the `Microsoft.Identity.Client` dependency when it's not needed, for example with [Chisel][1].

[1]: https://github.com/0xced/Chisel/

### CODE REVIEW

**Comment by cheenamalhotra** [comment]
Hi @0xced 

It seems there are test failures with this change, please address them to ensure the PR gets the right attention.

**Comment by 0xced** [comment]
Are the failures really related to this change?

I'm away from computer and Azure DevOps is barely usable on mobile so it's hard to see the test failures but I managed to see this one for example.

```
Microsoft.Data.SqlClient.SqlException : ManagedIdentityCredential authentication unavailable. The requested identity has not been assigned to this resource.
Status: 400 (Bad Request)
```

I have no idea how it relates to this change and where I should look to fix it. Do you have any idea?

**Comment by David-Engel** [comment]
> I have no idea how it relates to this change and where I should look to fix it. Do you have any idea?

Merge the latest from main. There were a bunch of recent fixes that should resolve test config/CI issues.

**Comment by 0xced** [comment]
That would be nice if someone from the SqlClient team could merge the main branch (I have allowed edits from maintainers). Else I'll do it in about a week.

**Review by David-Engel — APPROVED** [review]

**Review by DavoudEshtehari — APPROVED** [review]

**Pull request merged**
