### PR TITLE
Align whole comments between netfx and netcore

### PR DESCRIPTION
**Pull request by MichelZ**
All this PR does is deal with comments, so hopefully easy to review
Mostly removes obsolete comments from netfx to align netfx and netcore for later mering

Part of #2953

### CODE REVIEW

**Review by benrr101 — COMMENTED** [review]
To be honest I'm not sure about this one. I appreciate the efforts to make merging this class easier, but I'm also concerned about losing in-code documentation.

Questions for other reviewers:
* Are these TODOs actually done?
* What does tagging something as `UNDONE` actually mean?
* Is there any benefit to keeping old ticket IDs? I personally wouldn't even know where to go looking for them.

Would appreciate review from @ErikEJ or @Wraith2 before I approve

**Comment by MichelZ** [comment]
I‘m also happy to switch it around to add the info on the other side, if that‘s the concern.

AFAIK these things were removed on the netcore side before for a reason I guess

**Comment by ErikEJ** [comment]
I vote for keeping them for the purpose of merging.

**Comment by benrr101** [comment]
@ErikEJ Sorry, I'm a bit confused with that answer. Are you saying "leave the old ticket IDs until merging is completed then remove them", "leave old ticket IDs indefinitely", or something else?

Also what does `UNDONE` mean in these contexts? @cheenamalhotra @saurabh500

**Comment by ErikEJ** [comment]
@benrr101 postpone the decision to remove them (or not) ...

**Review by benrr101 — CHANGES_REQUESTED** [review]
As per the suggestion from @ErikEJ, let's retain the old ticket information and todo/undone tags. I think that more/less amounts to copying them from netfx to netcore. Although I personally like removing stuff, I don't want to lose any history if possible.

Thanks for your patience on this one 👍

**Comment by MichelZ** [comment]
OK, no worries. Will adjust

**Comment by MichelZ** [comment]
@benrr101 Done

**Review by benrr101 — APPROVED** [review]

**Review by mdaigle — APPROVED** [review]

**Review by cheenamalhotra — APPROVED** [review]

**Pull request merged**
