### PR TITLE
Move into shared for DbMetaDataFactory.cs 

### PR DESCRIPTION
**Pull request by lcheunglci**
Relates to #1261 . I moved the dotnet version of DbMetaDataFactory to the shared src and updated the reference in the netfx project to it because the netcore version uses the newer C# syntax and comments and code has been cleaned up.

### CODE REVIEW

**Comment by Wraith2** [comment]
How do you feel about updating the style of the code? There are lots of modern naming violations in there like these:

```
        private const string _collectionName = "CollectionName";
        private const string _populationMechanism = "PopulationMechanism";
        private const string _populationString = "PopulationString";
        private const string _maximumVersion = "MaximumVersion";
        private const string _minimumVersion = "MinimumVersion";
        private const string _dataSourceProductVersionNormalized = "DataSourceProductVersionNormalized";
        private const string _dataSourceProductVersion = "DataSourceProductVersion";
        private const string _restrictionDefault = "RestrictionDefault";
        private const string _restrictionNumber = "RestrictionNumber";
        private const string _numberOfRestrictions = "NumberOfRestrictions";
        private const string _restrictionName = "RestrictionName";
        private const string _parameterName = "ParameterName";
```

And things like `if (SupportedByCurrentVersion(row) == false)` which aren't _wrong_ as such but it would be nice to get cleaned up. In general when I'm working on a merge I turn on the info messages for the file and try to resolve as many of them according to the repo style as I can.

**Comment by lcheunglci** [comment]
> How do you feel about updating the style of the code? There are lots of modern naming violations in there like these:
> 
> ```
>         private const string _collectionName = "CollectionName";
>         private const string _populationMechanism = "PopulationMechanism";
>         private const string _populationString = "PopulationString";
>         private const string _maximumVersion = "MaximumVersion";
>         private const string _minimumVersion = "MinimumVersion";
>         private const string _dataSourceProductVersionNormalized = "DataSourceProductVersionNormalized";
>         private const string _dataSourceProductVersion = "DataSourceProductVersion";
>         private const string _restrictionDefault = "RestrictionDefault";
>         private const string _restrictionNumber = "RestrictionNumber";
>         private const string _numberOfRestrictions = "NumberOfRestrictions";
>         private const string _restrictionName = "RestrictionName";
>         private const string _parameterName = "ParameterName";
> ```
> 
> And things like `if (SupportedByCurrentVersion(row) == false)` which aren't _wrong_ as such but it would be nice to get cleaned up. In general when I'm working on a merge I turn on the info messages for the file and try to resolve as many of them according to the repo style as I can.

That's a great a idea, but perhaps, I'm missing something in my visual studio settings to get these info messages to show up for the file because I currently don't see any warning or info messages in my editor.  I was reading in the `coding-style.md` that there's a .editorconfig, but I'm not sure exactly how it works.

**Comment by Wraith2** [comment]
If I turn on info messages for this file I get this:

image

and each of those naming rule violations will correspnd to one of the constants. Instead of `_collectionName` it should not start with an underscore and should start with a capital, so `CollectionName`

**Comment by lcheunglci** [comment]
Thanks @Wraith2 , I'm able to see the same info messages in the error list panel as in your screenshot.  I'll fix them in my next commit.

**Comment by Wraith2** [comment]
The CI isn't happy but i don't think it's related to your changes, for example 
https://dev.azure.com/sqlclientdrivers-ci/sqlclient/_build/results?buildId=38974&view=logs&j=84415923-4175-5328-da83-e82a5e56172c&t=a9101a3f-4ee2-51f7-d19f-63edc33ee862&l=45 sadly it's usually a bit flaky so you end up having to check each failing leg to identify if it's important or infrastructure related,

**Comment by JRahnama** [comment]
> The CI isn't happy but i don't think it's related to your changes, for example
> https://dev.azure.com/sqlclientdrivers-ci/sqlclient/_build/results?buildId=38974&view=logs&j=84415923-4175-5328-da83-e82a5e56172c&t=a9101a3f-4ee2-51f7-d19f-63edc33ee862&l=45 sadly it's usually a bit flaky so you end up having to check each failing leg to identify if it's important or infrastructure related,

that has happened before. It is due to an unsuccessful database-drop act. I will trigger the tests to rerun and if not going well will do a clean up.

**Review by Kaur-Parminder — APPROVED** [review]

**Review by DavoudEshtehari — APPROVED** [review]
Good job 👍

**Pull request merged**
