### PR TITLE
Consolidate SSPI context generation to single abstraction

### PR DESCRIPTION
**Pull request by twsouthwick**
Part of #2253

### CODE REVIEW

**Comment by twsouthwick** [comment]
/azd run CI-SqlClient (Mac Azure SQL net7.0,AnyCPU,1)

**Review by arellegue — APPROVED** [review]
Looks good to me.

**Comment by twsouthwick** [comment]
@arellegue I keep getting errors on some of the builds for creating SQL user. What's the way to handle this?

image

**Comment by David-Engel** [comment]
> I keep getting errors on some of the builds for creating SQL user. What's the way to handle this?

It's a very annoying intermittent issue on the team's radar to fix. We usually rerun failed jobs and it works the next time.

**Comment by twsouthwick** [comment]
> > I keep getting errors on some of the builds for creating SQL user. What's the way to handle this?
> 
> It's a very annoying intermittent issue on the team's radar to fix. We usually rerun failed jobs and it works the next time.

Ok good - was trying to figure out how my change caused it :) I couldn't see a way to rerun it and the normal `/azp` commands I've used on other repos don't seem to rerun anything. Thanks for triggering it!

**Comment by David-Engel** [comment]
This is still on my radar. Just been busy. I'm currently trying to run our internal Kerberos test pipeline against your branch.

**Comment by twsouthwick** [comment]
@David-Engel Looks like there are conflicts now. Any eta on those tests you are trying to run?

**Comment by twsouthwick** [comment]
@David-Engel I see test failures, but I don't think they're due to my change. I've bucketed the failures into the following:

Mac error:

- On a test on mac: `System.PlatformNotSupportedException: Windows Principal functionality is not supported on this platform.`

-  `One or more errors occurred. (Database 'NORTHWIND' on server 'adotest-eus' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '{4BF18551-8BA0-4E47-911B-AE7D7DF81B18}'.)
  ---- Microsoft.Data.SqlClient.SqlException : Database 'NORTHWIND' on server 'adotest-eus' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '{4BF18551-8BA0-4E47-911B-AE7D7DF81B18}'.`

- Enclave tests have error `The job running on agent ADO-CI-AE-1ES-Pool 13 ran longer than the maximum time of 120 minutes. For more information, see https://go.microsoft.com/fwlink/?linkid=2077134`

Any action on my part for these?

**Review by David-Engel — APPROVED** [review]

**Comment by David-Engel** [comment]
No action needed on your part. The enclave failures are known infra issues. The one about Northwind seems random/intermittent. The mac one is strange. I'm re-running failed jobs to see if that one passes.

**Pull request merged**
