### PR TITLE
Improvement | Dispose RandomNumberGenerator object

### LINKED ISSUE #1494: dispose RandomNumberGenerator object #1478
dispose RandomNumberGenerator object #1478

### PR DESCRIPTION
**Pull request by EngRajabi**
Improvement | dispose RandomNumberGenerator object after generate randome bytes
fixes #1494

### CODE REVIEW

**Review by johnnypham — APPROVED** [review]

**Review by Kaur-Parminder — APPROVED** [review]

**Review by DavoudEshtehari — COMMENTED** [review]
Nice catch. Could you take care of the [AkvStoreProviderVerifyFunctionWithInvalidSignature](https://github.com/dotnet/SqlClient/blob/6c6c76ca4f4ead9a2ce4bdd8466aecb6b4003c34/src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/ExceptionTestAKVStore.cs#L221) too?

**Comment by EngRajabi** [comment]
Thanks for checking the code. I did not change the tests because dispose in the tests did not have a specific function.
I do not know why builds fail. Interestingly, a timeout error is received. Can you help me?

**Comment by EngRajabi** [comment]
@DavoudEshtehari @johnnypham @JRahnama @Kaur-Parminder  thanks

**Comment by JRahnama** [comment]
I just reran the failed pipelines, LGTM. that was nice catch @EngRajabi, well done.

**Review by JRahnama — APPROVED** [review]

**Review by mokarchi — APPROVED** [review]
That’s great @EngRajabi

**Comment by EngRajabi** [comment]
@DavoudEshtehari @Kaur-Parminder please check. thanks

**Comment by DavoudEshtehari** [comment]
> Thanks for checking the code. I did not change the tests because dispose in the tests did not have a specific function. I do not know why builds fail. Interestingly, a timeout error is received. Can you help me?

I believe you've updated the tests. I'd appreciate it if you could include the requested improvement in this PR for the sake of uniformity.

**Comment by EngRajabi** [comment]
Hello
Thank you for reviewing the request. @DavoudEshtehari @Kaur-Parminder

**Comment by johnnypham** [comment]
> Hello Thank you for reviewing the request. @DavoudEshtehari @Kaur-Parminder


If you can add one more dispose in [AkvStoreProviderVerifyFunctionWithInvalidSignature](https://github.com/dotnet/SqlClient/blob/6c6c76ca4f4ead9a2ce4bdd8466aecb6b4003c34/src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/ExceptionTestAKVStore.cs#L221), we can get this merged.

**Comment by EngRajabi** [comment]
> > Hello Thank you for reviewing the request. @DavoudEshtehari @Kaur-Parminder
> 
> If you can add one more dispose in [AkvStoreProviderVerifyFunctionWithInvalidSignature](https://github.com/dotnet/SqlClient/blob/6c6c76ca4f4ead9a2ce4bdd8466aecb6b4003c34/src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/ExceptionTestAKVStore.cs#L221), we can get this merged.

This part is inside the test.  Is it that important?

**Comment by EngRajabi** [comment]
@johnnypham done! please merge

**Review by DavoudEshtehari — APPROVED** [review]

**Comment by EngRajabi** [comment]
Please run the build. Bild fails because we are under sanctions

**Pull request merged**
