### PR TITLE
Replace public async void with public async Task for XUnit

### LINKED ISSUE #2947: XUnit does not support public async void in next version
The next version of XUnit does not support `public async void` in test methods.
This should be changed to `public async Task`

https://dotnet.social/@xunit/112265523775265162

More recent versions of XUnit 2.x also issue a Warning - which gets treated as an Error in this project.

### PR DESCRIPTION
**Pull request by MichelZ**
Fixes #2947

### CODE REVIEW

**Comment by MichelZ** [comment]
@dotnet-policy-service agree

**Review by mdaigle — APPROVED** [review]

**Review by benrr101 — APPROVED** [review]
Thanks for both reporting the issue and fixing the issue :D I think the likelihood that we'll upgrade xunit versions anytime soon is sorta slim - iirc there's a dependency issue with a library provided by the dotnet team, that won't work with a newer version. It's been like 7 months since I looked at that, so it might not be a concern anymore. But, regardless, this is the proper way to do async tests, so we should be doing this.

I'll kick off a CI build, and assuming it passes without issue (no reason it shouldn't), we'll get it merged 🚢

**Review by edwardneal — COMMENTED** [review]
Thanks for this - I didn't realise we were using `async void` anywhere.

I can see a bundle of other async void tests when I search for it in the solution. I can submit a PR to your branch with them if you want, unless they were excluded deliberately?

**Comment by MichelZ** [comment]
Hmm. I upgraded XUnit and it gave Warnings about these. I‘m not sure why it wouldn‘t warn about the others, but of course I/we can change them as well

**Comment by MichelZ** [comment]
I think the reason the others are not flagged is that they don't use the [Fact] or [Theory] attributes, but the [ConditionalTheory]. The analyzer probably ignores those. I'll update them as well

**Comment by MichelZ** [comment]
Done.

There are also async void's in the BenchmarkRunners for Benchmark.NET, I'm not too familiar with Benchmark.NET, so this might be on purpose? If not, I can also fix them in a separate PR.

Additionally, there is one async void in SNIPacket.cs here:
https://github.com/dotnet/SqlClient/blob/9d5ca32e666b3da1cc27b4ab145367308998b147/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNIPacket.cs#L330

Not sure if that needs fixing, too (in another PR)

**Comment by MichelZ** [comment]
> Thanks for both reporting the issue and fixing the issue :D I think the likelihood that we'll upgrade xunit versions anytime soon is sorta slim - iirc there's a dependency issue with a library provided by the dotnet team, that won't work with a newer version. It's been like 7 months since I looked at that, so it might not be a concern anymore. But, regardless, this is the proper way to do async tests, so we should be doing this.
> 
> I'll kick off a CI build, and assuming it passes without issue (no reason it shouldn't), we'll get it merged 🚢

You mean this comment?
https://github.com/dotnet/SqlClient/pull/2379#issuecomment-1979544650

Wasn't this fixed by upgrading to .NET8 now?

**Comment by MichelZ** [comment]
Let's see how TdsParser goes... 
I'm curious about SqlClientX and what the roadmap/timeframe looks for that

**Comment by benrr101** [comment]
> Do you think I can add a PR to upgrade to the latest versions?

Yknow what, I think you're right. Since we dropped net6 we should be able to take the latest version of Microsoft.DotNet.XUnitExtensions and probably take the latest of XUnit (might even be a requirement for the aforementioned). I'm always a bit hesitant with this codebase, but once this one is checked in, I would support a PR that upgrades XUnit/extensions

> I'm curious about SqlClientX and what the roadmap/timeframe looks for that
... same 😅

**Pull request merged**
