### PR TITLE
Code Cleanup | Fixing Inconsistent Modifiers

### PR DESCRIPTION
**Pull request by benrr101**
**Description**: One thing that lights up my IDE a lot is inconsistent ordering of modifiers for methods, properties, etc. This PR does a quick sweep of the codebase (automated) and reorders the modifiers to be consistent with C# standards.

**AI Analysis**: 
image

**Testing**: Well ... if it builds and passes the CI tests, I think it's good to go.

### CODE REVIEW

**Comment by saurabh500** [comment]
I like your changes, but this is going to cause me a lot of pain when I decided to merge the json stuff.

**Comment by roji** [comment]
For this kind of code style change, I'd highly recommend encoding the applied style in .editorconfig, so that discrepancies don't creep back in in the future.

**Comment by saurabh500** [comment]
Please hold off on the merge of this PR till we drive https://github.com/dotnet/SqlClient/pull/2714 and JSON work to conclusion.

**Comment by JRahnama** [comment]
@saurabh500 I think, we can also have [RoslynAnalyzer](https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/#enforce-team-coding-standards) to enforce some coding standards to prevent this in future as this cannot be done in editorconfig file.

**Comment by cheenamalhotra** [comment]
@benrr101 can you please resolve these conflicts?

**Comment by benrr101** [comment]
Closing as too many things have changed since last working on this. BUT I HAVEN'T GIVEN UP 😤

**Pull request closed without merging**
