### PR TITLE
Update Azure dependencies to latest stable versions

### PR DESCRIPTION
**Pull request by SimonCropp**
* Azure.Identity 1.12.0
 * Azure.Core 1.42.0
 * Azure.Security.KeyVault.Keys 4.6.0

### CODE REVIEW

**Comment by JRahnama** [comment]
I was wondering if we could apply the same approach to Azure.Core that @ErikEJ used for Microsoft.Identity.Client in PR #2577.

**Comment by cheenamalhotra** [comment]
@DavoudEshtehari Since the version bumps are minor versions - can this be tagged as a non-breaking change? Unless you want to elaborate your understanding here?

**Comment by DavoudEshtehari** [comment]
Thanks @cheenamalhotra, there was confusion due to a major version bump of a transient dependency affecting versions 4.0 and earlier, which does not apply here.

**Comment by cheenamalhotra** [comment]
@SimonCropp 

Please update as below (latest):
* Azure.Identity v1.12.1
* Azure.Core v1.44.0

**Pull request closed without merging**
