### PR TITLE
Update Release notes for Hotfix release

### PR DESCRIPTION
**Pull request by cheenamalhotra**

### CODE REVIEW

**Comment by ErikEJ** [comment]
@divega

**Comment by Wraith2** [comment]
hotfix @rmja

**Comment by rmja** [comment]
Thank you so much for this, and sorry for being persistent about it being released

**Comment by cheenamalhotra** [comment]
@rmja 

We recognized the severity of the issue and thanks for bringing it forward!

**Comment by divega** [comment]
:+1: thanks @rmja for giving us visibility into this issue and to @cheenamalhotra and @David-Engel for getting this fix through the door so swiftly.

**Pull request merged**
