### PR TITLE
Merge some metadata classes

### PR DESCRIPTION
**Pull request by Wraith2**
Another small set of merges. No noteworthy changes.

### CODE REVIEW

**Review by cheenamalhotra — APPROVED** [review]
LGTM!
Small note for reviewing team:
- There's a virtual `Close` method in netfx class `SmiRecordBuffer`, implemented in `TdsRecordSetterBuffer.cs` but is unused, seems to be safe for deletion.

**Comment by cheenamalhotra** [comment]
Just FYI..
We're looking into pipeline trigger issues recently happening, will let you know when we'd need a push on this branch to trigger CI builds again.

**Comment by cheenamalhotra** [comment]
The pipelines are back, could you try pushing an update to your PR?
e.g. "merge" from "dotnet/master"?

**Comment by Wraith2** [comment]
I looked at the Close implementation and originally pulled it into the netcore version but later tracing through what it did I realised it was totally dead code and re-removed it. So I did the due diligence even though it looks like I just took netcore.

Pipelines seem to be passed now...

**Comment by cheenamalhotra** [comment]
Yep I got that, just wanted to call out changes in case that raises questions.
FYI, the pipelines were not triggered, you'll have to check-in something for checks to run.

**Comment by Wraith2** [comment]
turned it off and then turned it on again, that triggered it 😁

**Comment by Wraith2** [comment]
The test failures are from a changed localized message that's being tested for directly. That seems a bit fragile and it isn't related to the changes that I've made in this PR.

**Comment by JRahnama** [comment]
LGTM.

**Review by JRahnama — APPROVED** [review]

**Review by DavoudEshtehari — APPROVED** [review]

**Pull request merged**
