### PR TITLE
Include new packages in nuspec file

### PR DESCRIPTION
**Pull request by DavoudEshtehari**
+ Alphabetically has been sorted.

### CODE REVIEW

**Comment by johnnypham** [comment]
The following are present in netcore csproj but still missing in the changes:

```<PackageReference Include="System.Security.Permissions" Version="$(SystemSecurityPermissionsVersion)" />
  <PackageReference Include="System.Threading.Tasks" Version="$(SystemThreadingTasksVersion)" />
  <PackageReference Include="System.Memory" Version="$(SystemMemoryVersion)" />
  <PackageReference Include="System.Globalization" Version="$(SystemGlobalizationVersion)" />
  <PackageReference Include="System.Xml.ReaderWriter" Version="$(SystemXmlReaderWriterVersion)" />
```

Should we include every package? @cheenamalhotra

**Comment by cheenamalhotra** [comment]
> The following are present in netcore csproj but still missing in the changes:
> 
> ```
>   <PackageReference Include="System.Threading.Tasks" Version="$(SystemThreadingTasksVersion)" />
>   <PackageReference Include="System.Memory" Version="$(SystemMemoryVersion)" />
>   <PackageReference Include="System.Globalization" Version="$(SystemGlobalizationVersion)" />
>   <PackageReference Include="System.Xml.ReaderWriter" Version="$(SystemXmlReaderWriterVersion)" />
> ```
> 
> Should we include every package? @cheenamalhotra

Good observation, I could build netcore project without these packages included.
If they're not needed, they could be removed perhaps? Can we try to remove them in this PR?

**Comment by DavoudEshtehari** [comment]
All the pipelines passed without those 4 package references on .NET Core, yesterday. Updated `Versions.props` too.

**Comment by JRahnama** [comment]
> You could consider building the nuget package using msbuild...

that is how we build the driver and tests, if I have got your point correct. Building driver using `msbuild -p:Configuration=$(Configuration)` will also lead to create a folder named package with the created `nuget` inside it.

**Comment by ErikEJ** [comment]
Yes, I meant define the package in the .csproj, this also makes dependency management much simpler

**Comment by cheenamalhotra** [comment]
Our process is distributed since we need to Sign the DLLs before packing when we build release packages. For that reason we build and pack in different steps, but we can investigate any possibilities to ease this process.

**Review by cheenamalhotra — APPROVED** [review]

**Review by JRahnama — APPROVED** [review]

**Pull request merged**
