### PR TITLE
docs: Update porting cheat sheet to include mention of backward incompable connection string changes

### PR DESCRIPTION
**Pull request by deadlydog**
docs: Update porting cheat sheet to include mention of backward incompatible connection string changes

Issue #2974

### CODE REVIEW

**Review by cheenamalhotra — APPROVED** [review]

**Comment by benrr101** [comment]
/azp run

... probably unnecessary, but just for safety sake

**Comment by benrr101** [comment]
@azure-pipelines you are a goofball

**Review by benrr101 — APPROVED** [review]

**Comment by deadlydog** [comment]
Wow, I'm impressed by the quick turnaround on reviewing this and merging it in. Thanks!

**Pull request merged**
