### PR TITLE
Chore | Upgrade IdentityModel dependencies

### PR DESCRIPTION
**Pull request by lcheunglci**
Relates to #1601, the dependencies for the IdentityClient, IdentityModel JWT and IDOC are updated to a newer stable version i.e. from 6.8.0 to 6.18.0.  I did notice when I checked again the latest version is now 6.19.0.  Not sure, if I should upgrade to that one instead.

### CODE REVIEW

**Comment by AraHaan** [comment]
Since 6.19.0 is the latest stable why not test 18.0 and then later test 19.0 to see which one works better, if nothing changes I guess then do 19.0.

**Comment by AraHaan** [comment]
Going to check 6.19.0 soon before settling with 6.18.0?

**Comment by lcheunglci** [comment]
Looks like there's another update since the last time I opened this PR for Identity.Client from 4.44.0 to 4.45.0 and IdentityModel.JsonWebToken and OpenIdConnect from 6.18.0 to 6.21.0, I'll update my PR to reflect that.

**Review by Kaur-Parminder — APPROVED** [review]

**Comment by AraHaan** [comment]
Hopefully Dependabot could be enabled for these too.

**Review by DavoudEshtehari — APPROVED** [review]

**Pull request merged**
